### ISSUE TITLE
UPSD issue - load_percent presented as both int and float blocks writes from one group

### ISSUE THREAD

**Issue by lpaseenba** [influxdata/telegraf#12501]
### Relevant telegraf.conf

```toml
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "120s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb_v2]]
  urls = ["$INFLUX_URL"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
[[inputs.upsd]]
```

### Logs from Telegraf

```text
telegraf --config /etc/telegraf/telegraf.conf --input-filter upsd --test --debug 2>&1|sed 's/server1/redacted/g'
2023-01-12T15:59:38Z I! Starting Telegraf 1.24.1
2023-01-12T15:59:38Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2023-01-12T15:59:38Z I! Loaded inputs: upsd
2023-01-12T15:59:38Z I! Loaded aggregators:
2023-01-12T15:59:38Z I! Loaded processors:
2023-01-12T15:59:38Z W! Outputs are not used in testing mode!
2023-01-12T15:59:38Z I! Tags enabled: host=redacted
2023-01-12T15:59:38Z D! [agent] Initializing plugins
2023-01-12T15:59:38Z D! [agent] Starting service inputs
2023-01-12T15:59:38Z D! [agent] Stopping service inputs
2023-01-12T15:59:38Z D! [agent] Input channel closed
2023-01-12T15:59:38Z D! [agent] Stopped Successfully
> upsd,host=redacted,model=Back-UPS\ ES\ 600M1,serial=4B2102P08698,status_OL=true,ups_name=ups battery_charge_percent=100i,battery_date="2021/01/06",battery_voltage=13.6,firmware="928.a8 .D",input_voltage=119,load_percent=8i,nominal_battery_voltage=12,nominal_input_voltage=120i,nominal_power=330i,status_flags=8i,time_left_ns=3480000000000i,ups_status="OL" 1673539179000000000

and

# telegraf --config /etc/telegraf/telegraf.conf --input-filter upsd --test --debug 2>&1|sed 's/server2/redacted2/g'
2023-01-12T16:02:08Z I! Starting Telegraf 1.24.2
2023-01-12T16:02:08Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2023-01-12T16:02:08Z I! Loaded inputs: upsd
2023-01-12T16:02:08Z I! Loaded aggregators:
2023-01-12T16:02:08Z I! Loaded processors:
2023-01-12T16:02:08Z W! Outputs are not used in testing mode!
2023-01-12T16:02:08Z I! Tags enabled: host=redacted2
2023-01-12T16:02:08Z D! [agent] Initializing plugins
2023-01-12T16:02:08Z D! [agent] Starting service inputs
> upsd,host=redacted2,model=Back-UPS\ CS\ 350,serial=4B2017P09801,status_OL=true,ups_name=ups battery_charge_percent=100i,battery_date="2020/04/27",battery_voltage=13.5,firmware="805.q14 .D",input_voltage=119,load_percent=17,nominal_battery_voltage=12,nominal_input_voltage=120i,nominal_power=210i,output_voltage=115,status_flags=8i,time_left_ns=4053000000000i,ups_status="OL" 1673539329000000000
2023-01-12T16:02:08Z D! [agent] Stopping service inputs
2023-01-12T16:02:08Z D! [agent] Input channel closed
2023-01-12T16:02:08Z D! [agent] Stopped Successfully
```

### System info

Ubuntu 20.04.4 LTS and Telegraf 1.24.2

### Steps to reproduce

1. run telegraf with [[inputs.upsd]] enabled with a UPS that provides load_percent without decimal and send data to influx
2. run telegraf with [[inputs.upsd]] enabled with a UPS that provides load_percent with decimal and send data to influx
3. whoever comes second fails

### Expected behavior

Always send data and in this case, always convert load_percent to float

### Actual behavior

only one or the other works

### Additional info

This is similar to issue #12461 in that it's a type problem. We collect info from many UPS models. One UPS model gives int and another model gives float

```$ upsc ups 2>/dev/null|grep -E "ups.load|device.model"
device.model: Back-UPS ES 600M1
ups.load: 7
```

```$ upsc ups 2>/dev/null|grep -E "ups.load|device.model"
device.model: Back-UPS CS 350
ups.load: 20.0
```

And this of course means we can only get upsd data from one group blocking all data from whoever comes second.

```
Jan 12 09:59:42 redacted telegraf[901]: 2023-01-12T14:59:42Z E! [outputs.influxdb_v2] Failed to write metric to test (will be dropped: 422 Unprocessable Entity): unprocessable entity: failure writing points to database: partial write: field type conflict: input field "load_percent" on measurement "upsd" is type integer, already exists as type float dropped=2
```

**Comment by danclough** [comment]
I'm also seeing this issue with ```battery.runtime```.  I have an APC SmartUPS unit which reports runtime as float, and a CyberPower which reports as int64.
```
# From the APC unit
battery.runtime: 1260.00

# From the CyberPower unit
battery.runtime: 50794
```

**Comment by lpaseenba** [comment]
Looking around and I found another value that causes data transmission to fail - "nominal_battery_voltage"

```
# source /etc/default/telegraf;sed "s~\$INFLUX_URL~$INFLUX_URL~;s~\${INFLUX_TOKEN}~${INFLUX_TOKEN}~;s~\${INFLUX_ORG}~${INFLUX_ORG}~;s~\${INFLUX_BUCKET}~${INFLUX_BUCKET}~" /etc/telegraf/telegraf.conf >/tmp/telegraf.conf
# telegraf --config /tmp/telegraf.conf --input-filter upsd --debug 2>&1|sed "s/$HOSTNAME/redacted1/g"
2023-01-13T22:33:43Z I! Starting Telegraf 1.24.3
2023-01-13T22:33:43Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2023-01-13T22:33:43Z I! Loaded inputs: upsd
2023-01-13T22:33:43Z I! Loaded aggregators:
2023-01-13T22:33:43Z I! Loaded processors:
2023-01-13T22:33:43Z I! Loaded outputs: influxdb_v2
2023-01-13T22:33:43Z I! Tags enabled: host=redacted1
2023-01-13T22:33:43Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"redacted1", Flush Interval:2m0s
2023-01-13T22:33:43Z D! [agent] Initializing plugins
2023-01-13T22:33:43Z D! [agent] Connecting outputs
2023-01-13T22:33:43Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2023-01-13T22:33:43Z D! [agent] Successfully connected to outputs.influxdb_v2
2023-01-13T22:33:43Z D! [agent] Starting service inputs
2023-01-13T22:35:44Z E! [outputs.influxdb_v2] Failed to write metric to btm_monitor (will be dropped: 422 Unprocessable Entity): unprocessable entity: failure writing points to database: partial write: field type conflict: input field "nominal_battery_voltage" on measurement "upsd" is type integer, already exists as type float dropped=2
2023-01-13T22:35:44Z D! [outputs.influxdb_v2] Wrote batch of 2 metrics in 718.328276ms
2023-01-13T22:35:44Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
```

**Comment by powersj** [comment]
My plan was to take all the [numeric values here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/upsd/upsd.go#L73-L87) and make them floats. I will take a look at the tests to see what is a string or int. If one of you wants to put up a PR it might go faster :) otherwise I will get to it next week.

**Comment by powersj** [comment]
I am not sure about `ups.temperature` `ups.realpower.nominal` or `input.frequency`. Do any of these ever show up as floats or are they always ints?

I have put up https://github.com/influxdata/telegraf/pull/12516 which will always convert the other fields to floats. There will be artifacts attached in 20-30mins. Can both of you give that a try and let me know about the additional fields?

Thanks!

**Comment by lpaseenba** [comment]
Thanks for quick response.

Quick test and I now get a complaint that it's sending float and it's int in the db, indicating that it should work once rolled out and the db change to next shar.

As for your other questions, on the 4 UPS models I have access to
**ups.temperature**:  031.5 - float
**ups.realpower.nominal**: 210 - int, it seems to be how many VA the UPS can deliver so doing float wouldn't hurt since it's at least not string
**input.frequency**:  60.00 - float

I also have an issue with some values missing possible because some are slightly different named but I will open a separate issue for that.

**Comment by powersj** [comment]
> ups.realpower.nominal: 210 - int, it seems to be how many VA the UPS can deliver so doing float wouldn't hurt since it's at least not string

This one is a little concerning as it will break existing users if it is already always an int, but I think catching all of these as floats is the right thing to do in case something changes down the road.

That said, I have pushed another change with those three values.

**Comment by lpaseenba** [comment]
One good thing is that if it's sent to influx then it will fix it self next time it changes shard (https://docs.influxdata.com/influxdb/v1.7/query_language/database_management/#shard-duration)
We just confirmed this because in the current shard `load_percent` is now `float` and all the ones still sending `int` fails.

**Comment by sabey** [comment]
this still persists in the latest release `Telegraf 1.30.1` for `nominal_battery_voltage`

```
2024-04-05T10:15:26Z E! [outputs.influxdb] E! [outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: field type conflict: input field "nominal_battery_voltage" on measurement "upsd" is type integer, already exists as type float dropped=1
```

**Comment by powersj** [comment]
And you set `force_float = true`? If so file a new issue with the requested information please.
