### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8d3597]

### ISSUE THREAD

**Issue by Bluefish67** [influxdata/telegraf#17606]
Hello, since today's update of the Telegraf Docker container installed on an Unraid server version 7.1.4, it is no longer running. What has changed to cause this error?
Here is the error:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8d3597]

goroutine 1 [running]:
github.com/influxdata/telegraf/selfstat.(*Collector).Register(0x0, {0xa6bfff8, 0x5}, {0xa6fc5b8, 0xd}, 0x0)
        /go/src/github.com/influxdata/telegraf/selfstat/collector.go:36 +0x77
github.com/influxdata/telegraf/plugins/outputs/influxdb.(*InfluxDB).Init(0xc00114bb08)
        /go/src/github.com/influxdata/telegraf/plugins/outputs/influxdb/influxdb.go:96 +0x22b
github.com/influxdata/telegraf/models.(*RunningOutput).Init(0x11c9fb30?)
        /go/src/github.com/influxdata/telegraf/models/running_output.go:165 +0xd6
github.com/influxdata/telegraf/agent.(*Agent).InitPlugins(0xc00248c010)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:254 +0x5e5
github.com/influxdata/telegraf/agent.(*Agent).Run(0xc00248c010, {0xb721170, 0xc0025986e0})
        /go/src/github.com/influxdata/telegraf/agent/agent.go:121 +0x357
main.(*Telegraf).runAgent(0xc00133c6e0, {0xb721170, 0xc0025986e0}, 0x0?)
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:565 +0x19e5
main.(*Telegraf).reloadLoop(0xc00133c6e0)
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf.go:207 +0x26b
main.(*Telegraf).Run(0xc00133c6e0)
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/telegraf_posix.go:20 +0xb8
main.runApp.func1(0xc00137dd40)
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/main.go:261 +0xdc9
github.com/urfave/cli/v2.(*Command).Run(0xc0013ca2c0, 0xc00137dd40, {0xc0000b20b0, 0x1, 0x1})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.7/command.go:276 +0x7c2
github.com/urfave/cli/v2.(*App).RunContext(0xc000b7fc00, {0xb720e80, 0x124353a0}, {0xc0000b20b0, 0x1, 0x1})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.7/app.go:333 +0x5a5
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.27.7/app.go:307
main.runApp({0xc0000b20b0, 0x1, 0x1}, {0xb66e100, 0xc0000f2070}, {0xb6a8260, 0xc000f85800}, {0xb6a8288, 0xc00122f500}, {0xb720d30, ...})
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/main.go:419 +0x11ff
main.main()
        /go/src/github.com/influxdata/telegraf/cmd/telegraf/main.go:433 +0xe8`

**Comment by IngmarStein** [comment]
Sounds like this was fixed with https://github.com/influxdata/telegraf/pull/17605 in v1.36.1?

**Comment by Bluefish67** [comment]
It says telegraf:latest for me, so I assume that (if an update is available) I will receive the latest version. Or am I misunderstanding “latest”? Because I'm still getting the error despite reinstalling.
I don't quite understand.

When I try to use telegraf:1.36.1, I get “not found.”

**Comment by srebhan** [comment]
@Bluefish67 the [docker PR](https://github.com/docker-library/official-images/pull/19836) is not merged yet so `latest` points to v1.36.0 until that PR is merged...

**Comment by Bluefish67** [comment]
Okay, I'll wait and see if anything happens. 
And to put it another way, aren't tests carried out before updates are released? It's really frustrating when you install an update and something that worked for months suddenly stops working.

**Comment by Bluefish67** [comment]
Great, update done and Telegraf is working again.
Great work, thumbs up!
