### ISSUE TITLE
[BUG][exec plugin] Support negative field values in v1.2.0

### ISSUE THREAD

**Issue by bbczeuz** [influxdata/telegraf#2368]
## Bug report
It seems that negative field values aren't supported anymore (v1.2). Earlier versions did support negative field values.

### Relevant telegraf.conf:
```
[[inputs.exec]]
commands = [
        "cat /tmp/test-lineproto.log"
]
timeout = "60s"
interval = "300s"
data_format = "influx"
```
### System info:
Centos 7, x86_64
Telegraf v1.2.0 (git: release-1.2 b2c1d98cff5a58d5ded3e74741c6bc32d6e789ee)

### Steps to reproduce:
1. Create a file '/tmp/test-lineproto.log' with the following contents (differences: Timestamps & 1st line has negative field values):
```
test_snri,dev=eth0,mac=10:20:30:40:50:60,rate=10000,vlan=120 level=-8i,noise=-32i,snr=24i 1486318300283457285
test_snri,dev=eth0,mac=10:20:30:40:50:60,rate=10000,vlan=125 level=8i,noise=32i,snr=24i 1486318400283457285
```
2. Start telegraf using `/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d -test --input-filter=exec`
3. Look at the output
4. Try the same without the `-test` parameter. Same results.

### Expected behavior:
```
$ /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d -test --input-filter=exec
* Plugin: inputs.exec, Collection 1
* Internal: 5m0s
> test_snri,dev=eth0,mac=10:20:30:40:50:60,rate=10000,vlan=120,host=vm0.localdomain level=-8i,noise=-32i,snr=24i 1486318300000000000
> test_snri,dev=eth0,mac=10:20:30:40:50:60,rate=10000,vlan=125,host=vm0.localdomain level=8i,noise=32i,snr=24i 1486318400000000000
```
### Actual behavior:
```
$ /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d -test --input-filter=exec
* Plugin: inputs.exec, Collection 1
* Internal: 5m0s
> test_snri,dev=eth0,mac=10:20:30:40:50:60,rate=10000,vlan=120,host=vm0.localdomain snr=24i 1486318300000000000
> test_snri,dev=eth0,mac=10:20:30:40:50:60,rate=10000,vlan=125,host=vm0.localdomain level=8i,noise=32i,snr=24i 1486318400000000000
```
### Additional info:

If I downgrade to `Telegraf v1.1.1 (git: release-1.1.0 94de9dca1fc6efb3a4bf3ec6869c356278c6755a)`, everything works as expected. If I manually insert values into InfluxDB v1.2, negative field values work as expected, so this seems to be Telegraf v1.2.0 related. There's definitively a test case needed

**Comment by sparrc** [comment]
this was a bug fixed in 1.2.1, please upgrade

**Comment by bbczeuz** [comment]
Version 1.2.0 is the newest version in the RPM as well as in the Debian repo. Bug is not yet fixed there. As I think (hope) most people use your software via the repos: Please update the repos.

**Comment by sparrc** [comment]
the repos will get updated soon, the latest versions are available on the downloads page
