### ISSUE TITLE
Proxmox plugin returns "Error in plugin: node_name not found"

### ISSUE THREAD

**Issue by davromaniak** [influxdata/telegraf#8300]
Hi.

Here's the issue I encounter while trying to activate the new proxmox input plugin

```
~# telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d/ --input-filter proxmox --test
2020-10-22T16:19:08Z I! Starting Telegraf 1.16.0
2020-10-22T16:19:08Z E! [inputs.proxmox] Error in plugin: node_name not found
2020-10-22T16:19:08Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```

### /etc/telegraf/telegraf.d/proxmox.conf:
```toml
[[inputs.proxmox]]
  base_url = "https://__host__.davromaniak.eu:8006/api2/json"
  api_token = "root@pam!xxxxxx-xxxxxxx"  
  insecure_skip_verify = false
  response_timeout = "5s"
```

### System info:
Telegraf 1.16.0 on Debian Buster 64bits (running Proxmox PVE, standalone node)

### Additional info:

When trying to perform the API call "manually", here's the result I get using the url "https://__host__.davromaniak.eu:8006/api2/json/nodes/__host__/dns" :
```json
{"data":{"search":"davromaniak.eu","dns1":"xxx.xxx.xxx.xxx"}}
```
__host__ being the hostname (not the FQDN)

I don't know if I missed something on this, don't hesitate to tell/ask me.

Thanks.

**Comment by liveware-problems** [comment]
I'm seeing the same error - node_name not found - can this be verified please?

**Comment by olsonnn** [comment]
Same issue here. Even commenting node_name (as it's optional) doesn't help. 
Permission issue?

**Comment by olsonnn** [comment]
i've got it working when using: 

  api_token = "root@pam!monitor=lalblalbal"
  ## Optional node name config
  node_name = "pve"

it seems root is required?!

**Comment by davromaniak** [comment]
Hi.

Even when I set the node name to the actual hostname (not FQDN), I have the "node_name not found".

I'll try to do some debug later today, but I'm not fluent in Go, so it will be kind of challenging.

Thanks.

**Comment by davromaniak** [comment]
Hi.

Well... I found the issue.

I don't know why, but my "/etc/resolv.conf" file was totally messed up and there was no default domain ("search ...").

I fixed this, rebooted the server and no issues right now.

**Comment by rare-magma** [comment]
Hi @davromaniak 
Could you please share more details on how you fixed your issue? Perhaps share your /etc/resolv.conf setup? I'm still facing the same error.

**Comment by davromaniak** [comment]
Hi.

Here it is.

`
search davro.tech
nameserver 213.186.33.99
`

When I had the issue, the "search" line wasn't here.

Thanks.

**Comment by codi639** [comment]
Hi @powersj,
Since you did not closed the issue I ask:
I'm working with a Telegraf instance located on the Proxmox host. I get the `E! [inputs.proxmox] Error in plugin: unexpected end of JSON input` with or without the node_name parameter...
There's my input Telegraf:
```toml
[[inputs.proxmox]]
  ## API connection configuration. The API token was introduced in Proxmox v6.2. Required permissions for user and token: PVEAuditor role on /.
  base_url = "https://172.16.20.11:8006/api2/json"
  api_token = "root@172.16.20.11!monitoring=59111b0a-.......-78931293a66d"

  #node_name = "tank"

  ## Optional TLS Config
  #tls_ca = "/etc/telegraf/local_proxmox.pem"
  #tls_cert = "/etc/telegraf/local_proxmox.pem"
  #tls_key = "/etc/telegraf/local_proxmox.pem"
  ## Use TLS but skip chain & host verification
  insecure_skip_verify = false

  # HTTP response timeout (default: 5s)
  response_timeout = "5s"
```

**Comment by llzzrrdd** [comment]
Can you kindly re-open this and all related issues with the "search domain is not set" error? It doesn't look like it is solved somehow, or I haven't noticed after all this time searching?
