### ISSUE TITLE
cgroups input ignores machine-qemu\x2d1\x2dvmname.scope directory

### ISSUE THREAD

**Issue by slynn1324** [influxdata/telegraf#8340]
### Relevant telegraf.conf:

```toml
# # Read specific statistics per cgroup
[[inputs.cgroup]]
#   ## Directories in which to look for files, globs are supported.
#   ## Consider restricting paths to the set of cgroups you really
#   ## want to monitor if you have a large number of cgroups, to avoid
#   ## any cardinality issues.
#   # paths = [
#   #   "/cgroup/memory",
#   #   "/cgroup/memory/child1",
#   #   "/cgroup/memory/child2/*",
#   # ]
    paths = [
        "/rootfs/sys/fs/cgroup/cpu/lxc.payload.*",
        "/rootfs/sys/fs/cgroup/cpu/machine.slice/machine-qemu*"
    ]
#    files = ["memory.*usage*", "memory.limit_in_bytes"]
#   ## cgroup stat fields, as file names, globs are supported.
#   ## these file names are appended to each path from above.
#   # files = ["memory.*usage*", "memory.limit_in_bytes"]
    files = ["cpuacct.usage"]
```

### System info:

Telegraf 1.16.0 in Docker (with appropriate rootfs mapped)
Ubuntu 20.04.1 

### Steps to reproduce:

1. ...  Run a VM with KVM+Libvirt
2. ... The above configuration will NOT pick up the cpuacct.usage statistic for /sys/fs/cgroup/cpu/machine.slice/machine-qemu*.  

### Expected behavior:

cgroup stats are read as normal

### Actual behavior:

Directory is ignored.  Additional directories are picked up as normal.

### Additional info:

I'm assuming this is due to the odd directory names that libvirt creates for each vm, but my Go skills are sparse to determine where the error might be in the cgroup plugin.  

As a work-around, I was able to create symlinks to a different directory ( e.g., /libvirt_cgroup/cpu/nginx -> '../../sys/fs/cgroup/cpu/machine.slice/machine-qemu\x2d1\x2dnginx.scope/'), and update the configuration to point to the new directory of symlinks - and it works correctly -- further enforcing that something with the '\x2' in the directory name is a likely culprit.

**Comment by sspaink** [comment]
@slynn1324 sorry you never got a response, have you tried the latest version of Telegraf to see if your still having this problem? I think it might have to do with the internal function to gather the directories but that has updated since this issue was created.

**Comment by slynn1324** [comment]
@sspaink I did just set this up again recently, and ran into the same issue with an updated release of Telegraf.  I probably need to look more closely again to fully confirm - but initial results didn't indicate that this was fixed.

**Comment by jakdept** [comment]
just tried this on telegraf 1.21.3 and 1.27.3, issue remains.

**Comment by powersj** [comment]
Hi,

Could you try one of the artifacts in https://github.com/influxdata/telegraf/issues/8340? It looks like we need to escape those backslashes.
