### ISSUE TITLE
After updating config.go, settings for parsers and measurement names are not taken

### ISSUE THREAD

**Issue by M0rdecay** [influxdata/telegraf#8362]
### Relevant telegraf.conf:
```toml
[[inputs.file]]
  files = [ "data.xml" ]
  name_override = "measurement_1"
  data_format = "value"
  data_type = "string"
```

### Expected behavior:
The telegraf will work with this configuration

### Actual behavior:
`2020-11-04T10:19:56Z E! [telegraf] Error running agent: Error loading config file some_data.conf: plugin inputs.file: line 1: configuration specified the fields ["name_override" "data_type"], but they weren't used`

### Additional info:
I ran into this while testing after updating my branch after merging this PR - https://github.com/influxdata/telegraf/pull/7583.
Parameters for the parser are now marked as unused.

After that, I builded telegraf from the master branch, after which I encountered the error described above.

@ssoroka, take a look, please. The situation is reproduced on the `master` build.

**Comment by ssoroka** [comment]
should be resolved now. Thanks for the report!

**Comment by danger89** [comment]
Telegraf 1.17.0 on Ubuntu Server 20.04 LTS. Same issue still:

```
Error loading config file /etc/telegraf/telegraf.conf: plugin inputs.exec: line 2324: configuration specified the fields ["date_type"], but they weren't used
```

**Comment by xakassi** [comment]
Hi guys!

I have a problem with Jolokia2 agent.

The config:
```
  # Metric declaration generates a Jolokia request to fetch telemetry from a JMX MBean.
  [[inputs.jolokia2_agent.metrics]]
    ## Measurement name.
    name  = "java_threading"
    ## The object name of a JMX MBean. MBean property-key values can contain a wildcard *, allowing you to fetch multiple MBeans with one declaration.
    mbean = "java.lang:type=Threading"
    ## A list of MBean attributes to read.
    paths = ["TotalStartedThreadCount", "ThreadCount", "DaemonThreadCount", "PeakThreadCount"]
```

And the error:
`Error running agent: Error loading config file /etc/telegraf/telegraf.conf: plugin inputs.jolokia2_agent: line 343: configuration specified the fields ["metrics"], but they weren't used`

Telegraf version is "1.17.3-alpine"

**Comment by M0rdecay** [comment]
@danger89 it seems you have specified the parameter incorrectly:
> configuration specified the fields ["**date_type**"], but they weren't used

please, try with `data_type`

**Comment by danger89** [comment]
Oopsy, let me check.
