### ISSUE TITLE
How to use outputs.sql plugin for postgres database

### ISSUE THREAD

**Issue by pavannayakanti** [influxdata/telegraf#9510]
Hello,

Am trying to push json data returning by an API to a postgres database using outputs.sql plugin.
However, i think am not understanding the right way to push the data to database.
As of now, my telegraf command ends up like this. 
```
[root@h0011939 ~]# telegraf --config /home/naypavk/src/telegraf/pullrequests.conf --test
2021-07-15T19:14:10Z I! Starting Telegraf 1.19.1
2021-07-15T19:14:10Z E! [telegraf] Error running agent: Error loading config file /home/naypavk/src/telegraf/pullrequests.conf: plugin inputs.http: line 100: configuration specified the fields ["driver" "timestamp_column" "table_template" "table_exists_template"], but they weren't used
[root@h0011939 ~]#
```
 Please advise.

here is the telegraf.conf file ...
```
# Telegraf Configuration
#
# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.
#
# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.
#
# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.
#
# Environment variables can be used anywhere in this config file, simply surround
# them with ${}. For strings the variable must be within quotes (ie, "${STR_VAR}"),
# for numbers and booleans they should be plain (ie, ${INT_VAR}, ${BOOL_VAR})


# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  # debug = false
  ## Log only error level messages.
  # quiet = false

  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  # logfile = ""

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Pick a timezone to use when logging or type 'local' for local time.
  ## Example: America/Chicago
  # log_with_timezone = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false
  
###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################


# Read formatted metrics from one or more HTTP endpoints
[[inputs.http]]
  ## One or more URLs from which to read formatted metrics
  urls = [
    "https://bitbucket-dev.associatesys.local/rest/api/1.0/dashboard/pull-requests?state=OPEN&participantStatus=UNAPPROVED&order=OLDEST"
  ]

  ## HTTP method
   method = "GET"

  ## Optional HTTP headers
  # headers = {"X-Special-Header" = "Special-Value"}
  headers = {"authorization" = "Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxx"}

  ## Amount of time allowed to complete the HTTP request
   timeout = "5s"

  ## List of success status codes
   success_status_codes = [200]

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
    data_format = "json"
	tag_keys = ["state"]
	name_override = "pull-requests"
	json_query = "values"
	json_string_fields = ["id", "title", "createdDate","updatedDate"]
   


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# # Send metrics to SQL Database
# [[outputs.sql]]
#   ## Database driver
#   ## Valid options: mssql (Microsoft SQL Server), mysql (MySQL), pgx (Postgres),
#   ##  sqlite (SQLite3), snowflake (snowflake.com)
        driver = "jdbc:postgresql://10.157.165.176:5432/"
#
#   ## Data source name
#   ## The format of the data source name is different for each database driver.
#   ## See the plugin readme for details.
#       data_source_name = "dnsfortos"
#
#   ## Timestamp column name
#       timestamp_column = "timestamp"
	    timestamp_column = "createdDate"
#
#   ## Table creation template
#   ## Available template variables:
#   ##  {TABLE} - table name as a quoted identifier
#   ##  {TABLELITERAL} - table name as a quoted string literal
#   ##  {COLUMNS} - column definitions (list of quoted identifiers and types)
#   # table_template = "CREATE TABLE {TABLE}({COLUMNS})"
      table_template = "CREATE TABLE [IF NOT EXISTS] tblpullrequests (id, title, createdDate, updatedDate)"

#
#   ## Table existence check template
#   ## Available template variables:
#   ##  {TABLE} - tablename as a quoted identifier
       table_exists_template = "SELECT 1 FROM {TABLE} LIMIT 1"
#
#	table_exists_template = "SELECT 1 FROM {tblpullrequests} LIMIT 1"
#   ## Initialization SQL
#   # init_sql = ""
#	 # init_sql = ""
#
#   ## Metric type to SQL type conversion
#   #[outputs.sql.convert]
#   #  integer              = "INT"
#   #  real                 = "DOUBLE"
#   #  text                 = "TEXT"
#   #  timestamp            = "TIMESTAMP"
#   #  defaultvalue         = "TEXT"
#   #  unsigned             = "UNSIGNED"
```

**Comment by srebhan** [comment]
I think you completely mixed up `driver` and `data_source_name`. If you are using Postgres, you need to set `driver = "pgx"` as the comment above the option says. Furthermore, `data_source_name` is a [Data source name (DSN)](https://en.wikipedia.org/wiki/Data_source_name) add can have the form `postgres://username:password@localhost:5432/database_name` for this driver. So you should start your sql config with
```toml
[[outputs.sql]]
  ## Database driver
  ## Valid options: mssql (Microsoft SQL Server), mysql (MySQL), pgx (Postgres),
  ##  sqlite (SQLite3), snowflake (snowflake.com)
  driver = "pgx"

  ## Data source name
  ## The format of the data source name is different for each database driver.
  ## See the plugin readme for details.
  data_source_name = "postgresql://10.157.165.176:5432/dnsfortos"

 ...
```

**Comment by pavannayakanti** [comment]
Thanks for correcting me @srebhan.
I have corrected the config file and here is the outcome...
`[root@h0011939 ~]# telegraf --config /home/naypavk/src/telegraf/pullrequests.conf --test
2021-07-16T17:33:53Z I! Starting Telegraf 1.19.1
2021-07-16T17:33:53Z E! [telegraf] Error running agent: Error loading config file /home/naypavk/src/telegraf/pullrequests.conf: plugin inputs.http: line 100: configuration specified the fields ["table_template" "driver"], but they weren't used
[root@h0011939 ~]#`

please advise. 

here is the content of output plugin of postgressql
`###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# # Send metrics to SQL Database
# [[outputs.sql]]
#   ## Database driver
#   ## Valid options: mssql (Microsoft SQL Server), mysql (MySQL), pgx (Postgres),
#   ##  sqlite (SQLite3), snowflake (snowflake.com)
        driver = "pgx"
#
#   ## Data source name
#   ## The format of the data source name is different for each database driver.
#   ## See the plugin readme for details.
#       data_source_name = "jdbc:postgresql://myuser:mypass@10.157.165.176:5432/bitbucketdb_dev"
#
#   ## Timestamp column name
#       timestamp_column = "timestamp"
	    #timestamp_column = "createdDate
#
#   ## Table creation template
#   ## Available template variables:
#   ##  {TABLE} - table name as a quoted identifier
#   ##  {TABLELITERAL} - table name as a quoted string literal
#   ##  {COLUMNS} - column definitions (list of quoted identifiers and types)
#   # table_template = "CREATE TABLE {TABLE}({COLUMNS})"
      table_template = "CREATE TABLE IF NOT EXISTS tblpullrequests (id, title, createdDate, updatedDate)"
	#   table_template="CREATE TABLE IF NOT EXISTS {TABLE}({COLUMNS}); SELECT create_hypertable({TABLELITERAL},'time',chunk_time_interval := INTERVAL '1 week',if_not_exists := true);"

#
#   ## Table existence check template
#   ## Available template variables:
#   ##  {TABLE} - tablename as a quoted identifier
#
#	table_exists_template = "SELECT 1 FROM {tblpullrequests} LIMIT 1"
#   ## Initialization SQL
#   # init_sql = ""
#	 # init_sql = ""
#
#   ## Metric type to SQL type conversion
#   #[outputs.sql.convert]
#   #  integer              = "INT"
#   #  real                 = "DOUBLE"
#   #  text                 = "TEXT"
#   #  timestamp            = "TIMESTAMP"
#   #  defaultvalue         = "TEXT"
#   #  unsigned             = "UNSIGNED"
`

**Comment by srebhan** [comment]
@pavannayakanti you still have the section (`# [[outputs.sql]]`) commented... This way TOML fails as it cannot assign `driver` to any section...

**Comment by pavannayakanti** [comment]
Yes @srebhan , i realized it and corrected. 
Now the script doesn't throws any error, but i don't get to see any changes happening in the database end. no db or table gets created. not sure, what am missing here now. any advise?

**Comment by srebhan** [comment]
@pavannayakanti did that fix your issue? If so, please close it here.

**Comment by pavannayakanti** [comment]
please close the issue. thanks for your support.
